### ISSUE TITLE
Add support to query and graph external metrics

### ISSUE THREAD

**Issue by dgzlopes** [grafana/k6-cloud-feature-requests#15]
It's awesome that:
- k6 can output the results to different backends.
- k6 cloud can output the results to different APM providers.

But, when I want to visualize and understand my test results, I miss something: **external metrics**.

Yup, I would love to query and graph external metrics on k6 to correlate-all-the-things!

For example: Connect my Prometheus instance to k6 Cloud, query my availability SLI for the foo service, and graph the values of that metric side-by-side with the k6 ones.

I've some things in mind for k6 OSS (being able to use external metrics as native ones), but this feature is only about the cloud.

**Comment by dgzlopes** [comment]
Well, I think we don't have a query language for the metrics in the cloud. I suppose that's a requirement... Or maybe this can be tackled in some other way.

**Comment by sniku** [comment]
I think the most natural way to view metrics from multiple sources is to use a generic dashboarding solution like Grafana. 
We will release a k6 cloud Grafana connector in the coming weeks. Once that's done, you should be able to correlate metrics from k6 cloud with other sources. 

We are also working on adding PromQL query language to k6 cloud backend. This will significantly simplify querying k6 cloud metrics from other tools.  (CC: @esquonk)

**Comment by dgzlopes** [comment]
Yup, fully agree. I just thought that k6 Cloud could be a better place to visualize and correlate all the things. But I like Grafana :)

Uuu, that's really cool! Full support?

**Comment by dgzlopes** [comment]
btw, feel free to close this :)
