### ISSUE TITLE
Ability to define groups/pages using the Chrome Recorder

### ISSUE THREAD

**Issue by tom-miseur** [grafana/k6-cloud-feature-requests#23]
As a... 
- Chrome Recorder user

I want... 
- The ability to set groups/pages during recording using the extension UI

So that...
- I can set group names as I'm interacting with the website and don't need to log this separately
- I can see which HTTP requests belong to a particular higher-level action (e.g. "Submit Login" could consist of multiple HTTP requests, and I might not realize that when looking at captured requests later on)
- I don't have to rely on the automatic grouping functionality as it can sometimes get things wrong

Also worth considering:
- An option to generate a function for each group, which could then be used to generate an `export default function` that calls these functions (rather than generating a single lengthy function containing everything)

**Comment by markjmeier** [comment]
Closing as part of moving things to Grafana Feature requests / Will reference this issue in the broad discussion about recorders
