### ISSUE TITLE
`handleSummary()` support in k6 cloud

### ISSUE THREAD

**Issue by na--** [grafana/k6-cloud-feature-requests#24]
The `handleSummary()` functionality (https://github.com/loadimpact/k6/pull/1768) that was recently [released in k6 v0.30.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) only works in local `k6 run` tests for now, not in `k6 cloud`.

That means being able to view the exact same summary (including any custom output and files `handleSummary()` generates) on the local machine that executed the `k6 cloud` command, as if you had ran the same script with `k6 run`, despite the fact it might have been executed on hundreds of different instances in our cloud!

I'm adding this issue to gauge interest in `k6 cloud` support for this feature, so, please :+1: this issue if you'd like us to prioritize this task. We'll also use the issue to track the effort when we actually start implementing it.

**Comment by ppcano** [comment]
Ideally, the `handleSummary` in `k6 cloud` could also provide the cloud test URL  -> `http://app.k6.io/runs/xxxx`.

Making available the cloud test URL will allow any `handleSummary` integration to link to the entire test results in the k6 Cloud web application.

**Comment by adshead** [comment]
I would really like this feature as we have a custom handleSummary method producing custom metrics in a csv file that runs on an Azure pipeline. However because handleSummary doesn't run in the cloud it means we can't run our tests in different regions and produce a csv file because of handleSummary not running. Please please add this feature

**Comment by robingustafsson** [comment]
Thanks @adshead for adding your vote!

**Comment by imx-hcordero** [comment]
My team and I are also facing the same issue, we would like to export the test results on the release pipeline. Please consider the change/fix.

**Comment by markjmeier** [comment]
@imx-hcordero thanks for the feedback - we absolutely have this in our head, however its strangely blocked by things which means we cant just implement it.

That said - Im also working to port ideas from this repo over to the process Grafana uses for FR.  If you can work with support or your account team to raise this as a feature request, I'll make sure you are tracked appropriately!

Closing this issue as I have ported it.
