### ISSUE TITLE
Comparisons are difficult between test runs 

### ISSUE THREAD

**Issue by rhires** [grafana/k6-cloud-feature-requests#32]
I would like to be able to name the test runs, or use the existing “Note” functionality, to more easily distinguish between two side-by-side test runs, instead of having meaningless datetime timestamps, because when doing the testing, we change a variable, and it would be useful to be able to see what that variable is via the name. For example, “LB with 2 servers” vs “LB with 4 servers” is much more meaningful than “Aug 23, 10:13" vs “Aug 22, 10:13”

**Comment by robingustafsson** [comment]
I take it this is refering to the select box for picking a test run to compare against. Makes sense to have access to the note there as well for easier identification of test runs.

This request is also related to support for tagging on the test run level: https://github.com/grafana/k6-cloud-feature-requests/issues/2

**Comment by rhires** [comment]
This is one place 
![image](https://user-images.githubusercontent.com/12577765/130796336-c9f466eb-1b92-404d-bffc-e7f8a4112274.png)

and here is another: 
![image](https://user-images.githubusercontent.com/12577765/130796513-6b922732-b851-452e-9159-836635bc8821.png)

**Comment by robingustafsson** [comment]
Got it, thanks. @legander @majavojnoska This should be a relatively quick project to include in the next product cycle right?

**Comment by majavojnoska** [comment]
Already on it @robingustafsson!

**Comment by EdvinasDaugirdas** [comment]
The improvement has been released and is now live (app version 1.3.0) 🚀
