### ISSUE TITLE
Add baseline indicator in comparison dropdown menu

### ISSUE THREAD

**Issue by nicolevanderhoeven** [grafana/k6-cloud-feature-requests#33]
My most common use case for the test comparison feature is comparing a recent test run to the baseline. However, in the dropdown menu for "Select a test run" (see screenshot), it's not easy to spot which test my baseline is, even if I've previously marked it as a baseline. I would love a star indicator next to the baseline test to make this easier, or even a "compare to baseline" option.

![k6_cloud-compare_test](https://user-images.githubusercontent.com/36070553/130753166-ad5a5ee6-ec6c-4709-b6cf-658f7194b0e9.png)

**Comment by EdvinasDaugirdas** [comment]
Star indicator added to the dropdown menu (app version 1.3.0) ⭐

![Screenshot 2021-09-28 at 15 53 13](https://user-images.githubusercontent.com/10167318/135090675-341ea8f6-bbea-4cae-b1ae-c60613e2b369.png)
