### ISSUE TITLE
Comparison chart in Analysis tab should display a chart for both tests when in comparison mode

### ISSUE THREAD

**Issue by tom-miseur** [grafana/k6-cloud-feature-requests#34]
Currently, only a single chart is visible in the Analysis tab even when one is comparing between two test runs. We should display both charts here.

We may also want to consider renaming `Comparison chart` to something else to prevent confusion over what is being compared (metrics vs. two tests). I think it might make sense for it not to have a name at all, or for it to show the timestamp (or note, should we implement #32).

**Comment by gopinatheth** [comment]
Good feature to have.
