### ISSUE TITLE
Option to generate shareable / "magic" link in notifications

### ISSUE THREAD

**Issue by tom-miseur** [grafana/k6-cloud-feature-requests#38]
To make it easier to share results with users that do not have a k6 Cloud account, we should add an option for notifications to include the shareable / "magic" link in addition to, or as an alternative to, the regular link to a test result.

**Comment by robingustafsson** [comment]
We reviewed this feature request for the next product cycle, it looks smaller than it actually is. Before we can start on this feature we'd first need to solve how consent to generating public ID/URL should work. We've gottent requests to be able to turn this feature on and off completely at the organizational level but consent to auto-generate public ID/URL is probably better done on the project or test level.

**Comment by markjmeier** [comment]
closing as we no longer have magic links in GCk6
