### ISSUE TITLE
Configure different notifications per project

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-cloud-feature-requests#42]
Teams organize their testing on various projects. Projects might have different members, scopes, and ways of testing. Projects provide the context for different purposes. 

As a common case, a user might want to be notified of test failures only on the most critical projects. 

This feature requests to allow configuring [Notifications](https://k6.io/docs/cloud/manage/notifications/) per project. And it is related to #40 ( **3 - Enable Cloud APM integration per project to automatically export test result metrics**)

**Comment by burck1** [comment]
I gave this issue a 👍  as I had originally submitted this as a support ticket:

> Is there an easy way to filter notifications by project? We have successfully setup Microsoft Teams notifications, but at the moment the notifications are too verbose to be useful. The main reason being that we have multiple engineering teams using k6 with separate k6 projects for their different products and at the moment all notifications for all projects go the the same Microsoft Teams channel. If we had a way to filter by k6 project when we setup the notifications then we could route notifications to the correct engineering team rather than using a shared channel. If this is not possible to do today, can we submit this as a feature request?

Tom asked if there was a way to filter [incoming webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) on the Microsoft Teams side, but unfortunately there is not and easy way to do this (that I can find).

**Comment by markjmeier** [comment]
Moved this into Grafana Feature Requests. Closing issue to follow the process there.
