### ISSUE TITLE
OpenID and role mapping support

### ISSUE THREAD

**Issue by joe-hutchinson-cko** [grafana/k6-cloud-feature-requests#44]
It would be useful to be able to assign member roles and project membership via SSO provider such as Okta. This enables centralised management of permissions within an organisation.

**Comment by robingustafsson** [comment]
Thanks for the feature request @joe-hutchinson-cko. As part of #25 we intend to allow mapping of an incoming SAML attribute to a team and role as part of account provisioning via SAML SSO. A user would be assigned access to projects according to the team's permissions. Would this be enough to cover your use case?

**Comment by joe-hutchinson-cko** [comment]
Hi @robingustafsson yes that'll cover my request. The feature would need to support the removal of users if removed from a an Okta group.

**Comment by markjmeier** [comment]
This feature was implemented as part of teams in k6 cloud.

We are currently working on this feature as part of Grafana cloud k6.  Closing this issue as this work is in flight and will be delivered in the next few months / This repo is being migrated to Grafana Feature requests
