### ISSUE TITLE
Allow Users to change default Project/Organization

### ISSUE THREAD

**Issue by mpandurovic** [grafana/k6-cloud-feature-requests#48]
As a member of multiple organizations/projects when I run a k6 script from CLI without a specified `projectID` in `options.ext.loadimpact`, my test run is assigned to a default organization/project. However, default organization/project cannot be changed in the k6 cloud app, so I'm "stuck" in one forever. This feature could be useful to users since some of them create a trial account (which becomes default) before joining a larger organization where they run more tests.

**Comment by markjmeier** [comment]
ported to grafana feature requests
