### ISSUE TITLE
More information in Slack message/report

### ISSUE THREAD

**Issue by strmecki** [grafana/k6-cloud-feature-requests#50]
Slack notifications are currently very basic and then contain links to see check the test results in the app:
<img width="550" alt="Screenshot 2022-02-23 at 11 55 40" src="https://user-images.githubusercontent.com/57947228/155306577-469ff7a1-e21a-451a-865b-4e9a5aa0ce31.png">

It would be nice for Slack notifications to contain a summary with a comparison with previous test runs.
This way we could easily spot any issue without actually having to log in to the app every day.

For comparision, this is how Lighthouse Slack report looks like:
<img width="470" alt="Screenshot 2022-02-23 at 11 55 53" src="https://user-images.githubusercontent.com/57947228/155305990-c1fe51bb-0622-4adc-99aa-680963c0e29e.png">

Thanks,
Daniel

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
