### ISSUE TITLE
PDF Summary Report Suggestions

### ISSUE THREAD

**Issue by markjmeier** [grafana/k6-cloud-feature-requests#51]
The PDF summary is a useful feature, however there are some areas where it's utility can be improved to increase the usefulness: 

Idea: Allow PDF summaries for aborted tests (at least aborted by user)
Reason: Users sometimes abort tests when they see a system is not coping with the load. There can still be valid data to put into a report. 

Idea:  Pass notes from `options.ext.loadimpact.note` into the PDF summary. 
Reason: The note feature is often used to provide additional context to a test. At least inserting this into the "summary" section of PDF summary can let the end user decide if it should stay or not

Idea: Improve how we handle URLs in the report
Currently the report shares the top 10 slowest URLs. For tests with a large number of URLs, many get dropped. Depending on what the person running the test wants to highlight, they may not have the correct url metrics to include. Giving users some method of choosing what URL metrics to add will enhance usability.

**Comment by Vmihajlovic** [comment]
One thing to add here would be to allow automatic PDF generation/export over API. This feature was requested on multiple occasions through customer conversations and support.

This would probably be out of scope for changes/improvements suggested above but would fall under PDF improvements.

**Comment by markjmeier** [comment]
PDF summary is changing for Grafana Cloud k6 and the output of custom dashboards can be exported as PDF. 

>allow automatic PDF generation/export over API 

is supported via custom dashboards
