### ISSUE TITLE
Disable shareable public test run links on org/project level

### ISSUE THREAD

**Issue by Vmihajlovic** [grafana/k6-cloud-feature-requests#53]
This feature was requested a few times from larger clients with a stronger focus on security. It would enable project/team owners and admins to disable results link sharing on a specific project or on the entire organization.

**Comment by markjmeier** [comment]
Initially, I think we should allow admins to turn this on and off organization wide.  

Once we have better user management, it seems natural to allow admins to turn this on for specific projects
