### ISSUE TITLE
RPS when there are zero requests

### ISSUE THREAD

**Issue by burck1** [grafana/k6-cloud-feature-requests#54]
_I had originally submitted this as a support ticket but the helpful support engineer directed me to submit the request here._

We are reporting a custom RPS metric during our tests where we expect the RPS to be zero during a portion of the test. We think that the RPS is in fact zero, but the graphs within k6 cloud look like they attempt to connect the data points instead of showing zero RPS or showing an absence of data. Is there some way to get the graphs to show as zero RPS or to show a gap in the data? If not, can we submit this as a bug or feature request?

![graph_a](https://user-images.githubusercontent.com/2439306/163417415-29376528-160e-4338-960c-2297b9db5d22.png)

![graph_b](https://user-images.githubusercontent.com/2439306/163417451-54278cd2-70d9-4f27-8f12-1f96c282e8c5.png)

In the support ticket Tom indicated that "Behind-the-scenes, we use the Highcharts library, and it would appear that the library does indeed support the concept of a "null" entry that should break up the line to indicate lack of data."

Additionally, in our k6 script we have something like:

```js
import http from 'k6/http';
import { Counter } from 'k6/metrics';

const httpReqsEast = new Counter('http_reqs/us_east_1');
const httpReqsWest = new Counter('http_reqs/us_west_1');
const httpReqsOther = new Counter('http_reqs/other');

export default function () {
  const res = http.get('https://foo.example.com/bar');
  const region = res.json().region
  if (region === 'us-east-1') {
    httpReqsEast.add(1);
  } else if (region === 'us-west-2') {
    httpReqsWest.add(1);
  } else {
    httpReqsOther.add(1);
  }
}
```

We are up for suggestions for other ways to do this. Or maybe there is something we can add to our script to force a zero value?

```js
import http from 'k6/http';
import { Counter } from 'k6/metrics';

const httpReqsEast = new Counter('http_reqs/us_east_1');
const httpReqsWest = new Counter('http_reqs/us_west_1');
const httpReqsOther = new Counter('http_reqs/other');

export default function () {
  const res = http.get('https://foo.example.com/bar');
  const region = res.json().region
  if (region === 'us-east-1') {
    httpReqsEast.add(1);
    // can we even do this???
    httpReqsWest.add(0);
    httpReqsOther.add(0);
  } else if (region === 'us-west-2') {
    httpReqsEast.add(0);
    httpReqsWest.add(1);
    httpReqsOther.add(0);
  } else {
    httpReqsEast.add(0);
    httpReqsWest.add(0);
    httpReqsOther.add(1);
  }
}
```

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
