### ISSUE TITLE
Allow for configuring notification on a per-project basis

### ISSUE THREAD

**Issue by JordanNazemi** [grafana/k6-cloud-feature-requests#56]
We plan on using K6 Cloud for several different product teams. We currently have it set up that any failing tests send a Slack alert to a general #k6-alerts channel. However, some developers have requested we set up a Slack channel on a per-project basis so they're only notified by a failure that pertains to their product team. 

It would be a nice QOL feature to be able to do this natively in K6 Clouds notification system.

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
