### ISSUE TITLE
Making custom metrics configurable

### ISSUE THREAD

**Issue by tillkruss** [grafana/k6-cloud-feature-requests#57]
We have 10-12 custom metrics and currently we need to hand pick each metrics in a tiny modal for every single test run to be visible in the Analytics tab.

It's tedious and makes them unusable.

Would it be possible to customize which custom metrics are listed in the Analysis tab via the `const options` object in the test code, or a similar solution?

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
