### ISSUE TITLE
Add autorefresh/interval picker

### ISSUE THREAD

**Issue by dgzlopes** [grafana/k6-cloud-feature-requests#6]
I think having some kind of global autorefresh/interval picker for all the charts on the analysis tab can be useful.

Perhaps it can be disabled by default. Here's an example:
![refresh](https://user-images.githubusercontent.com/8228060/110342226-73390d80-802b-11eb-94f3-04910d82b313.gif)

**Comment by robingustafsson** [comment]
Hm, first I didn't understand this feature request 😅 (thinking surely it's auto-refreshing like the other data on the result page), but after checking the analysis tab I see it's not auto-refreshing data like the rest of the result page, and I don't know why, or at least don't remeber why it's done like that, so I'll have to check with the frontend team 🤔
