### ISSUE TITLE
Creating a projects using K6 cli or REST API

### ISSUE THREAD

**Issue by jinwoov** [grafana/k6-cloud-feature-requests#60]
Looking through the [doc](https://developers.k6.io/#tag/v4.0-load-tests), I noticed that document doesn't provide a way to create a project programmatically. I also search through option in the command line tool and I wasn't able to find anything. Would love a feature to codify a this process, so we can automate this process in our CI.

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
