### ISSUE TITLE
k6 cloud api for adding users to Projects 

### ISSUE THREAD

**Issue by akshaychopra5207** [grafana/k6-cloud-feature-requests#63]
### Feature description

k6 cloud api for adding users to Projects 

Instead of manually assigning user to the project. Api is required so that this can be automated

### How does this help you?

Reduce toil by automation. if we have an user api , the process of assigning users to the projects can be automated

### How often do you come across needing a feature like this?

Weekly

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
