### ISSUE TITLE
Host private modules to be used in many test scripts

### ISSUE THREAD

**Issue by mpszczolinski** [grafana/k6-cloud-feature-requests#65]
### Feature description

When using k6.io, there's no way to host custom made(private) modules that can be imported and used in multiple test scripts.

If many test scripts shares some logic a JS script must be either: stored in filesystem and run from CLI or stored in external S3 bucket.

It would be an obvious choice to upload such shared js file to k6 cloud and be able to import it in scripts hosted in k6.io UI (without need to using CLI when not needed).

### How does this help you?

In my organisation many test scripts shares same logic. Currently there's no easy way to put this logic in single file (e.g. talabat-k6-helpers.js) and use it in k6.io UI.

### How often do you come across needing a feature like this?

Daily

### Anything else to add?

I contacted support and they said such feature does not exist.

**Comment by dgzlopes** [comment]
Thanks for opening this @mpszczolinski!

Are you using the script editor that we provide in the Cloud?
