### ISSUE TITLE
Pricing is wrong for Grafana Cloud K6 - please improve it

### ISSUE THREAD

**Issue by joslat** [grafana/k6-cloud-feature-requests#66]
### Feature description

The pricing is VU hours which is rounded by VU. and a pro account has 500 VU h max per month.
This is wrong in many aspects as does not support the open model and short lived tests:

1. it forbids the usage of the k6 Open model which becomes prohibitive: If I have a test where I preallocate 500 VU, and use the test for 5 minutes, it becomes 500 VU h used. So cannot test anything else.
2. It goes against simple, short lived tests.
3. It does the rounding wrong (apparently to me). For example i have a test that uses 10 VU for 1 minute, this should be adding the VU minutes and then rounding them up to 1 VU hour. At the moment this seems to consume 10 VU hour...

Can you change:

1. The rounding calculation (add VU consumption and then round up)
2. Change this to VU minute.

This would make the pricing schema operative (at the moment it is not correct not fair) to my eyes, "it's a bug" ;)

### How does this help you?

there will be a more fair pricing and short lived tests are not expensive, also the calculation will be improved.
And k6 open model (arrival rate) are feasible too.

### How often do you come across needing a feature like this?

None

**Comment by dgzlopes** [comment]
Thanks for opening the issue, @joslat!

We are working on changing the pricing model as we speak to something that is pretty much in line with your proposal. 

We will be sharing more details about this pretty soon :+1:

**Comment by markjmeier** [comment]
@joslat I wanted to let know that we have released the new metering algorithm It's the default for all new customers.  As @dgzlopes noted - it's essentially in line with what you mention.  

Practical example:

Old model:  100 VUs for 10 minutes = 100 VUh
New model: 100 Vus for 10 minutes = 16.67 VUh

Important to note: **Existing customers** will need to work with their account team to make the necessary changes to their account/contract.
