### ISSUE TITLE
Re-assigning tests and associated data to different projects

### ISSUE THREAD

**Issue by ckbedwell** [grafana/k6-cloud-feature-requests#67]
### Feature description

Being able to re-assign a test and its associated data to a different / new project.

### How does this help you?

As I've grown more confident in my understanding of k6 and what tests I want to perform I've often found my projects grow increasingly messy and less organised.

I would love to have the ability to reassign tests and their associated data to a different project so that as my collection of tests grow I can ensure their organisation so it is easier and more satisfying to use the application.

### How often do you come across needing a feature like this?

Weekly

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
