### ISSUE TITLE
Save analysis charts when sharing test runs

### ISSUE THREAD

**Issue by na--** [grafana/k6-cloud-feature-requests#7]
> When I run a cloud test and create analysis charts, I do not see those same charts when the test run is shared.

from https://community.k6.io/t/analysis-charts-not-shared/1486

**Comment by robingustafsson** [comment]
This is something that's been requested previously as well. Also, something we'd like to add as an option when sharing a public URL to a test run.

This is related to https://github.com/k6io/cloud-feature-requests/issues/8 and will likely be lumped together when scheduled for implementation.

**Comment by markjmeier** [comment]
Right now you can use dashboards in Grafana cloud to share this type of data. We are working to improve the analysis tab in GCk6 to make exporting to dashboards easier.
