### ISSUE TITLE
Apply custom analysis dashboard/ view across multiple scenarios and share with other members of the organisation

### ISSUE THREAD

**Issue by phil-lee-feeld** [grafana/k6-cloud-feature-requests#70]
### Feature description

The feature centres specifically around the 'Analysis' tab with K6 cloud and the ability to not only apply/ set as default the configured custom view on the given scenario but also apply it to other scenarios and share it with other users within my organisation. Currently you have to setup the analysis views separately within each scenario.

### How does this help you?

Not only can it be time consuming to setup a custom analysis view any minor change results in the change being needed across all scenarios where the view is needed. 

Additionally, colleagues are unable to see the views I have configured and have to set them up individually. 

It would be of great help if one view can be setup at the organisation level and be available for users, in the K6 organisation, to apply them across any number of scenarios.

### How often do you come across needing a feature like this?

Daily

**Comment by dgzlopes** [comment]
Thank you for the feature request @phil-lee-feeld  :bow: 

cc @markjmeier

**Comment by markjmeier** [comment]
This issue has been migrated to Grafana Feature requests (please contact support or your account team to submit additional ideas or to add to this one)
